### ISSUE TITLE
minor issue: empty search output when not found

### ISSUE THREAD

**Issue by alexjonesinfowars** [adedomin/neo8ball-irc#15]
I can't really label this a 'bug', but maybe consider returning a productive message like "not found" (maybe reuse the 404 message) when querying for non existent moose. Right now, it just returns "Moose found: ".

**Comment by adedomin** [comment]
https://github.com/adedomin/neo8ball-irc/commit/2cd5e32b249521c3e927b2cdd89a09e0e5599066
